version: "3.7"

services:
  db:
    container_name: db
    image: postgis/postgis:11-2.5-alpine
    networks:
      - inner
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"

  pg_backup:
    container_name: pg_backup
    build: .
    env_file:
      - ./.env
    environment:
      - "GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}"
      - "GOOGLE_BUCKET_NAME=${GOOGLE_BUCKET_NAME}"
      - "ENCRYPTION_PRIVATE_KEY=${ENCRYPTION_PRIVATE_KEY}"
      - "ENCRYPTION_PUBLIC_KEY=${ENCRYPTION_PUBLIC_KEY}"
      - "ENCRYPTION_PASSPHRASE=${ENCRYPTION_PASSPHRASE}"
      - "DATABASE_BACKUP_PATH=${DATABASE_BACKUP_PATH}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD={POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - .:/app
    tty: true
    networks:
      - inner

volumes:
  data: {}

networks:
  inner:
